### ISSUE TITLE
Git Intro Should Have Helpful Links

### ISSUE THREAD

**Issue by jeffstjean** [UWO-Aero-Design/first-commit#7]
Anytime a new user "should" have something, we should include a link or something helpful for when they don't have that particular _thing_.

- [x] Installation of an IDE (VSCode?)
- [x] Installation of a compiler or interpreter (NodeJS?)
- [x] Introduction to command line
- [x] Installation of GitBash for Windows users
- [x] Link to Windows Terminal from the Microsoft Store
- [x] Instructions for setting powershell to default VSCode terminal

**Comment by zach1590** [comment]
I added all of these yesterday, so I think we can close this
